In [6]:
import requests
import requests
import pandas as pd
import pickle
import os
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go
import time
import numpy as np
import plotly.io as pio
from tqdm import tqdm
from datetime import datetime
from dateutil.relativedelta import relativedelta

pd.options.mode.chained_assignment = None
pio.renderers.default='notebook'

df_sp500 = pd.read_csv('sp500_tickers.csv')
tickers = df_sp500['Symbol'].values

sp500_close_fileo = open('sp500_close.pickle', 'rb')
close_datao = pickle.load(sp500_close_fileo)

sp500_inc_df = pd.read_pickle('income_statement_df.pkl')

sp500_inc_df

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome,stock,dateplus,120D_stock_change
0,2021-12-31,USD,33555000000,89113000000,55558000000,None,13694000000,19621000000,None,19861000000,...,1998000000,4738000000,31978000000,28530000000,38714000000,38790000000,31978000000,BAC,2022-04-30,-0.293161
1,2020-12-31,USD,19750000000,85528000000,65778000000,None,974000000,17858000000,None,18776000000,...,1101000000,8225000000,17894000000,22871000000,27220000000,27315000000,17894000000,BAC,2021-04-30,0.268443
2,2019-12-31,USD,32754000000,91244000000,58490000000,None,13024000000,16865000000,None,19730000000,...,5324000000,22345000000,27430000000,33008000000,55099000000,55211000000,27430000000,BAC,2020-04-29,-0.546397
3,2018-12-31,USD,34584000000,91020000000,56663000000,22619000000,20417000000,13160000000,None,14167000000,...,6437000000,20066000000,28147000000,24231000000,53191000000,53729000000,28147000000,BAC,2019-04-30,0.068999
4,2017-12-31,USD,29213000000,87126000000,58139000000,16308000000,-15284000000,43123000000,None,44497000000,...,10981000000,12912000000,18232000000,18438000000,41553000000,42174000000,18232000000,BAC,2018-04-30,-0.069519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2021-12-31,USD,-6031564000,647986000,3200334000,1608037000,-2552348000,891452000,None,1592297000,...,5267000,3499816000,-4506587000,-4551556000,-2401320000,-1700475000,-4506587000,NCLH,2022-04-30,-0.03994
1,2020-12-31,USD,-4253126000,1162118000,5415244000,1693061000,-3484135000,745345000,None,3070982000,...,12467000,103679000,-4012514000,-3957141000,-3906848000,-3189008000,-4012514000,NCLH,2021-04-30,0.270531
2,2019-12-31,USD,-223016000,6185140000,6408156000,3862961000,1178077000,974850000,None,1621038000,...,-18863000,286297000,930228000,796385000,1184265000,1830453000,930228000,NCLH,2020-04-29,-3.913321
3,2018-12-31,USD,-158591000,5758580000,5917171000,3576576000,1219061000,897929000,None,1458989000,...,14467000,276746000,954843000,766230000,1239710000,1800770000,954843000,NCLH,2019-04-30,0.087959
4,2017-12-31,USD,206338000,5396175000,5189837000,3906125000,1048819000,773755000,None,1283712000,...,10742000,243900000,759872000,1101311000,1038414000,1548371000,759872000,NCLH,2018-04-30,-0.135964