Import data from a CSV

In [6]:
import pandas as pd
df = pd.read_csv('Zip_Zri_MultiFamilyResidenceRental.csv')
df

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
0,61639,10025,New York,NY,New York-Newark-Jersey City,New York County,1,2930.0,2952.0,2926.0,...,3484.0,3523.0,3573.0,3622.0,3664.0,3698.0,3704.0,3692.0,3715.0,3676.0
1,84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,1447.0,1465.0,1469.0,...,1731.0,1749.0,1768.0,1787.0,1801.0,1806.0,1789.0,1761.0,1747.0,1731.0
2,61637,10023,New York,NY,New York-Newark-Jersey City,New York County,3,2797.0,2811.0,2813.0,...,3449.0,3459.0,3479.0,3491.0,3510.0,3521.0,3574.0,3608.0,3561.0,NaN
3,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,NaN,NaN,NaN,...,1226.0,1250.0,1264.0,1251.0,1246.0,1252.0,1280.0,1310.0,1294.0,1286.0
4,84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,1437.0,1469.0,1490.0,...,1888.0,1911.0,1934.0,1950.0,1953.0,1952.0,1921.0,1958.0,NaN,1916.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,90755,75202,Dallas,TX,Dallas-Fort Worth-Arlington,Dallas County,1857,997.0,1019.0,1042.0,...,1615.0,1619.0,1628.0,NaN,NaN,1729.0,1697.0,1739.0,NaN,NaN
1857,94610,84627,Ephraim,UT,NaN,Sanpete County,1858,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1298.0,NaN
1858,84452,60301,Oak Park,IL,Chicago-Naperville-Elgin,Cook County,1859,NaN,NaN,NaN,...,1447.0,1483.0,1495.0,1511.0,1537.0,1570.0,1580.0,1625.0,NaN,NaN
1859,94629,84647,Mount Pleasant,UT,NaN,Sanpete County,1860,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1221.0
1860,91695,77046,Houston,TX,Houston-The Woodlands-Sugar Land,Harris County,1861,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get a single column

In [7]:
df['State']

0       NY
1       IL
2       NY
3       TX
4       IL
        ..
1856    TX
1857    UT
1858    IL
1859    UT
1860    TX
Name: State, Length: 1861, dtype: object

Get a list of columns

In [9]:
df[['State','Metro']]

     State                             Metro
0       NY       New York-Newark-Jersey City
1       IL          Chicago-Naperville-Elgin
2       NY       New York-Newark-Jersey City
3       TX  Houston-The Woodlands-Sugar Land
4       IL          Chicago-Naperville-Elgin
...    ...                               ...
1856    TX       Dallas-Fort Worth-Arlington
1857    UT                               NaN
1858    IL          Chicago-Naperville-Elgin
1859    UT                               NaN
1860    TX  Houston-The Woodlands-Sugar Land

[1861 rows x 2 columns]

Filter based on values in a single column

In [14]:
df[df['State']=='OR']

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
117,99142,97229,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,118,NaN,NaN,NaN,...,1433.0,1437.0,1435.0,1456.0,1474.0,1491.0,1512.0,1514.0,1517.0,1528.0
221,99252,97402,Eugene,OR,Eugene,Lane County,222,682.0,679.0,685.0,...,1167.0,1179.0,1194.0,1205.0,1218.0,1223.0,NaN,NaN,NaN,NaN
325,99251,97401,Eugene,OR,Eugene,Lane County,326,NaN,NaN,NaN,...,1273.0,1280.0,1296.0,1318.0,1330.0,1339.0,NaN,NaN,NaN,NaN
361,99093,97124,Hillsboro,OR,Portland-Vancouver-Hillsboro,Washington County,362,NaN,NaN,NaN,...,1526.0,1517.0,1510.0,1503.0,1506.0,1508.0,1515.0,1519.0,1513.0,1517.0
396,99120,97206,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,397,NaN,NaN,NaN,...,1393.0,1392.0,1394.0,NaN,1484.0,1497.0,NaN,1574.0,1594.0,1602.0
422,99255,97405,Eugene,OR,Eugene,Lane County,423,NaN,NaN,NaN,...,1316.0,1320.0,1318.0,1320.0,1320.0,1327.0,NaN,NaN,NaN,NaN
479,99338,97501,Medford,OR,Medford,Jackson County,480,739.0,739.0,740.0,...,1156.0,1154.0,1150.0,1161.0,1192.0,1218.0,1232.0,NaN,NaN,NaN
570,99116,97202,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,571,NaN,975.0,981.0,...,1481.0,1477.0,1482.0,NaN,1598.0,1620.0,1648.0,1674.0,1685.0,1661.0
576,99012,97006,Beaverton,OR,Portland-Vancouver-Hillsboro,Washington County,577,NaN,NaN,NaN,...,1449.0,1455.0,1462.0,1468.0,1468.0,1471.0,1494.0,1500.0,1488.0,1483.0
597,99013,97007,Beaverton,OR,Portland-Vancouver-Hillsboro,Washington County,598,NaN,NaN,NaN,...,NaN,1338.0,1354.0,1376.0,1400.0,1414.0,1436.0,1442.0,1443.0,1454.0
641,99414,97756,Redmond,OR,Bend-Redmond,Deschutes County,642,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740,99034,97030,Gresham,OR,Portland-Vancouver-Hillsboro,Multnomah County,741,NaN,NaN,NaN,...,1376.0,1367.0,1360.0,1378.0,1386.0,1398.0,NaN,1493.0,1514.0,1544.0
790,99317,97477,Springfield,OR,Eugene,Lane County,791,NaN,NaN,NaN,...,1033.0,1026.0,1024.0,1028.0,1046.0,NaN,NaN,NaN,NaN,NaN
809,99131,97217,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,810,NaN,NaN,NaN,...,NaN,NaN,NaN,1575.0,1600.0,1629.0,NaN,1737.0,1719.0,1682.0
956,99123,97209,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,957,NaN,NaN,NaN,...,1731.0,1732.0,1734.0,1742.0,1735.0,1746.0,1772.0,1783.0,1733.0,1750.0
987,99128,97214,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,988,988.0,992.0,1005.0,...,1547.0,1548.0,1560.0,NaN,1641.0,1649.0,1633.0,1632.0,1631.0,1636.0
998,99318,97478,Springfield,OR,Eugene,Lane County,999,616.0,627.0,631.0,...,998.0,1001.0,1013.0,1037.0,1066.0,1086.0,NaN,NaN,NaN,NaN
1258,99066,97070,Wilsonville,OR,Portland-Vancouver-Hillsboro,Clackamas County,1259,NaN,NaN,NaN,...,1344.0,1350.0,1352.0,1361.0,1369.0,1377.0,1387.0,1384.0,1378.0,1383.0
1265,99060,97062,Tualatin,OR,Portland-Vancouver-Hillsboro,Washington County,1266,NaN,NaN,NaN,...,NaN,NaN,1401.0,1418.0,1436.0,1457.0,1461.0,1453.0,1444.0,1464.0
1333,99039,97035,Lake Oswego,OR,Portland-Vancouver-Hillsboro,Clackamas County,1334,NaN,NaN,NaN,...,1515.0,1530.0,1554.0,1577.0,1602.0,1626.0,1622.0,1608.0,1619.0,1604.0
1388,99115,97201,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,1389,NaN,NaN,NaN,...,1538.0,1531.0,1529.0,1533.0,1540.0,1547.0,1573.0,1560.0,1549.0,1542.0
1524,99149,97239,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,1525,NaN,NaN,NaN,...,1610.0,1606.0,1603.0,1620.0,1630.0,1632.0,1647.0,1668.0,1670.0,1657.0
1588,99038,97034,Lake Oswego,OR,Portland-Vancouver-Hillsboro,Clackamas County,1589,NaN,NaN,NaN,...,NaN,1903.0,1915.0,1926.0,1928.0,1900.0,NaN,NaN,1740.0,1773.0
1648,99145,97232,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,1649,NaN,NaN,NaN,...,1629.0,1620.0,1615.0,1645.0,1663.0,1666.0,1664.0,1656.0,1657.0,1678.0

Filter based on values in multiple columns

In [19]:
df[(df['City']=='Portland')&(df['RegionName']==97229)]

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,...,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
117,99142,97229,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,118,NaN,NaN,NaN,...,1433.0,1437.0,1435.0,1456.0,1474.0,1491.0,1512.0,1514.0,1517.0,1528.0